<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE mast[
<!ELEMENT mast (model, alphabet, motifs, sequences, runtime)>
<!ATTLIST mast version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model (command_line, max_correlation, remove_correlated, strand_handling, translate_dna, max_seq_evalue,
    adj_hit_pvalue, max_hit_pvalue, max_weak_pvalue, host, when)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT max_correlation (#PCDATA)>
<!ELEMENT remove_correlated EMPTY>
<!ATTLIST remove_correlated value (y|n) #REQUIRED>
<!ELEMENT strand_handling EMPTY>
<!ATTLIST strand_handling value (combine|separate|norc|protein) #REQUIRED>
<!ELEMENT translate_dna EMPTY>
<!ATTLIST translate_dna value (y|n) #REQUIRED>
<!ELEMENT max_seq_evalue (#PCDATA)>
<!ELEMENT adj_hit_pvalue EMPTY>
<!ATTLIST adj_hit_pvalue value (y|n) #REQUIRED>
<!ELEMENT max_hit_pvalue (#PCDATA)>
<!ELEMENT max_weak_pvalue (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!ELEMENT alphabet (letter+)>
<!ATTLIST alphabet type (amino-acid|nucleotide) #REQUIRED bg_source (preset|file|sequence_composition) #REQUIRED bg_file CDATA #IMPLIED>
<!ELEMENT letter EMPTY>
<!ATTLIST letter symbol CDATA #REQUIRED ambig (y|n) "n" bg_value CDATA #IMPLIED>
<!ELEMENT motifs (motif+,correlation*,nos*)>
<!ATTLIST motifs source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED>
<!ELEMENT motif EMPTY>
<!-- num is simply the loading order of the motif, it's superfluous but makes things easier for XSLT -->
<!ATTLIST motif id ID #REQUIRED num CDATA #REQUIRED name CDATA #REQUIRED width CDATA #REQUIRED
   best_f CDATA #REQUIRED best_r CDATA #IMPLIED bad (y|n) "n">
<!-- for n > 1 motifs there should be (n * (n - 1)) / 2 correlations, obviously there are none for only 1 motif -->
<!ELEMENT correlation EMPTY>
<!ATTLIST correlation motif_a IDREF #REQUIRED motif_b IDREF #REQUIRED value CDATA #REQUIRED>
<!-- nos: Nominal Order and Spacing diagram, a rarely used feature where mast can adjust pvalues for an expected motif spacing -->
<!ELEMENT nos (expect+)>
<!-- length is in the same unit as the motifs, which is not always the same unit as the sequence -->
<!ATTLIST nos length CDATA #REQUIRED>
<!-- the expect tags are expected to be ordered by pos ascending -->
<!ELEMENT expect EMPTY>
<!ATTLIST expect pos CDATA #REQUIRED gap CDATA #REQUIRED motif IDREF #REQUIRED>
<!ELEMENT sequences (database+, sequence*)>
<!-- the database tags are expected to be ordered in file specification order -->
<!ELEMENT database EMPTY>
<!ATTLIST database id ID #REQUIRED num CDATA #REQUIRED source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED 
    seq_count CDATA #REQUIRED residue_count CDATA #REQUIRED type (amino-acid|nucleotide) #REQUIRED link CDATA #IMPLIED>
<!-- the sequence tags are expected to be ordered by best combined p-value (of contained score tags) ascending -->
<!ELEMENT sequence (score+,seg*)>
<!ATTLIST sequence id ID #REQUIRED db IDREF #REQUIRED num CDATA #REQUIRED name CDATA #REQUIRED comment CDATA "" length CDATA #REQUIRED>
<!ELEMENT score EMPTY>
<!-- frame is the starting offset for translation of dna sequences which gives the lowest pvalues for the provided protein motifs -->
<!ATTLIST score strand (both|forward|reverse) #REQUIRED frame (a|b|c) #IMPLIED combined_pvalue CDATA #REQUIRED evalue CDATA #REQUIRED>
<!-- within each sequence the seg tags are expected to be ordered by start ascending -->
<!ELEMENT seg (data,hit+)>
<!ATTLIST seg start CDATA #REQUIRED>
<!ELEMENT data (#PCDATA)>
<!-- within each seg the hit tags are expected to be ordered by pos ascending and then forward strand first -->
<!ELEMENT hit EMPTY>
<!-- gap, while superfluous, makes creating motif diagrams for the text version much easier when using XSLT -->
<!ATTLIST hit pos CDATA #REQUIRED gap CDATA #REQUIRED motif IDREF #REQUIRED pvalue CDATA #REQUIRED strand (forward|reverse) "forward" 
    match CDATA #REQUIRED translation CDATA #IMPLIED>
<!ELEMENT runtime EMPTY>
<!ATTLIST runtime cycles CDATA #REQUIRED seconds CDATA #REQUIRED>
]>
<mast version="4.8.0" release="Wed Jan 11 15:32:51 EST 2012">
	<model>
		<command_line>mast meme.adh.zoops adh.s</command_line>
		<max_correlation>0.60</max_correlation>
		<remove_correlated value="n"/>
		<strand_handling value="protein"/>
		<translate_dna value="n"/>
		<max_seq_evalue>10</max_seq_evalue>
		<adj_hit_pvalue value="n"/>
		<max_hit_pvalue>0.0001</max_hit_pvalue>
		<max_weak_pvalue>0.0001</max_weak_pvalue>
		<host>tlb-takumi-lt.imb.uq.edu.au</host>
		<when>Wed Jan 11 17:18:05 2012</when>
	</model>
	<alphabet type="amino-acid" bg_source="preset">
		<letter symbol="A" bg_value="0.073"/>
		<letter symbol="C" bg_value="0.018"/>
		<letter symbol="D" bg_value="0.052"/>
		<letter symbol="E" bg_value="0.062"/>
		<letter symbol="F" bg_value="0.040"/>
		<letter symbol="G" bg_value="0.069"/>
		<letter symbol="H" bg_value="0.022"/>
		<letter symbol="I" bg_value="0.056"/>
		<letter symbol="K" bg_value="0.092"/>
		<letter symbol="L" bg_value="0.023"/>
		<letter symbol="M" bg_value="0.046"/>
		<letter symbol="N" bg_value="0.051"/>
		<letter symbol="P" bg_value="0.052"/>
		<letter symbol="Q" bg_value="0.074"/>
		<letter symbol="R" bg_value="0.059"/>
		<letter symbol="S" bg_value="0.000"/>
		<letter symbol="T" bg_value="0.064"/>
		<letter symbol="V" bg_value="0.001"/>
		<letter symbol="W" bg_value="0.033"/>
		<letter symbol="Y" bg_value="0.000"/>
	</alphabet>
	<motifs source="meme.adh.zoops" name="meme.adh.zoops" last_mod_date="Wed Jan 11 17:17:55 2012">
		<motif id="motif_1" num="1" name="1" width="21" best_f="GKVVLITGCSSGIGKATAKHL"/>
		<motif id="motif_2" num="2" name="2" width="29" best_f="SVYCASKFAVRMLTRSMAMEYAPHGIRVN"/>
		<correlation motif_a="motif_1" motif_b="motif_2" value="0.29"/>
	</motifs>
	<sequences>
		<database id="db_1" num="1" source="adh.s" name="adh.s" last_mod_date="Wed Jan 11 17:17:32 2012" seq_count="33" residue_count="9996" type="amino-acid"/>
		<sequence id="seq_1_22" db="db_1" num="22" name="YRTP_BACSU" comment="HYPOTHETICAL 25.3 KD PROTEIN IN RTP 5'REGION (ORF238)" length="238">
			<score strand="both" combined_pvalue="2.73e-45" evalue="9e-44"/>
			<seg start="1">
				<data>
MQSLQHKTALITGGGRGIGRATALALAKEGVNIGLIGRTSANVEKVAEEVKALGVKAAFAAADVKDADQVNQAVA
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="7.6e-19" match="+++++++++++++++++++++"/>
			</seg>
			<seg start="76">
				<data>
QVKEQLGDIDILINNAGISKFGGFLDLSADEWENIIQVNLMGVYHVTRAVLPEMIERKAGDIINISSTAGQRGAA
				</data>
				<hit pos="117" gap="90" motif="motif_2" pvalue="6.2e-05" match=" ++  + + +  + +  + ++     +  "/>
			</seg>
			<seg start="151">
				<data>
VTSAYSASKFAVLGLTESLMQEVRKHNIRVSALTPSTVASDMSIELNLTDGNPEKVMQPEDLAEYMVAQLKLDPR
				</data>
				<hit pos="153" gap="7" motif="motif_2" pvalue="7.2e-34" match="++++++++++ ++++++++++++++++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_8" db="db_1" num="8" name="BUDC_KLETE" comment="ACETOIN(DIACETYL) REDUCTASE (EC 1.1.1.5) (ACETOIN DEHYDROGENASE)" length="241">
			<score strand="both" combined_pvalue="3.38e-44" evalue="1.1e-42"/>
			<seg start="1">
				<data>
MQKVALVTGAGQGIGKAIALRLVKDGFAVAIADYNDATATAVAAEINQAGGRAVAIKVDVSRRDQVFAAVEQARK
ALGGFNVIVNNAGIAPSTPIESITEEIVDRVYNINVKGVIWGMQAAVEAFKKEGHGGKIVNACSQAGHVGNPELA
VYSSSKFAVRGLTQTAARDLAPLGITVNGFCPGIVKTPMWAEIDRQCRKRRANRWATARLNLPNASPLAACRSLK
				</data>
				<hit pos="2" gap="1" motif="motif_1" pvalue="1.8e-20" match="+++++++++++++++++++++"/>
				<hit pos="57" gap="34" motif="motif_2" pvalue="6.9e-06" match=" +  +    + + ++ +++ ++  ++ ++"/>
				<hit pos="150" gap="64" motif="motif_2" pvalue="3.8e-31" match="+++++++++++++++++++++++ +++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_14" db="db_1" num="14" name="FIXR_BRAJA" comment="FIXR PROTEIN" length="278">
			<score strand="both" combined_pvalue="1.15e-38" evalue="3.8e-37"/>
			<seg start="1">
				<data>
MGLDLPNDNLIRGPLPEAHLDRLVDAVNARVDRGEPKVMLLTGASRGIGHATAKLFSEAGWRIISCARQPFDGER
				</data>
				<hit pos="36" gap="35" motif="motif_1" pvalue="2.3e-17" match=" ++++ +++++++++++++ +"/>
			</seg>
			<seg start="151">
				<data>
APILLAQGLFDELRAASGSIVNVTSIAGSRVHPFAGSAYATSKAALASLTRELAHDYAPHGIRVNAIAPGEIRTD
				</data>
				<hit pos="187" gap="130" motif="motif_2" pvalue="8.2e-29" match="+++  +++++ ++++++++++++++++++"/>
			</seg>
			<seg start="226">
				<data>
MLSPDAEARVVASIPLRRVGTPDEVAKVIFFLCSDAASYVTGAEVPINGGQHL
				</data>
				<hit pos="250" gap="34" motif="motif_1" pvalue="7.7e-05" match="  +++   ++    + +  + "/>
			</seg>
		</sequence>
		<sequence id="seq_1_4" db="db_1" num="4" name="AP27_MOUSE" comment="ADIPOCYTE P27 PROTEIN (AP27)" length="244">
			<score strand="both" combined_pvalue="7.72e-37" evalue="2.5e-35"/>
			<seg start="1">
				<data>
MKLNFSGLRALVTGAGKGIGRDTVKALHASGAKVVAVTRTNSDLVSLAKECPGIEPVCVDLGDWDATEKALGGIG
				</data>
				<hit pos="7" gap="6" motif="motif_1" pvalue="2.5e-16" match="+ +++++++++++++ +++++"/>
				<hit pos="32" gap="4" motif="motif_1" pvalue="9.9e-05" match=" +++ ++  ++ +     +  "/>
			</seg>
			<seg start="76">
				<data>
PVDLLVNNAALVIMQPFLEVTKEAFDRSFSVNLRSVFQVSQMVARDMINRGVPGSIVNVSSMVAHVTFPNLITYS
STKGAMTMLTKAMAMELGPHKIRVNSVNPTVVLTDMGKKVSADPEFARKLKERHPLRKFAEVEDVVNSILFLLSD
				</data>
				<hit pos="102" gap="49" motif="motif_2" pvalue="1.9e-05" match=" + +    ++   ++  ++++   ++  +"/>
				<hit pos="147" gap="16" motif="motif_2" pvalue="7.1e-28" match="  ++++++++++++++++++++++ ++++"/>
				<hit pos="178" gap="2" motif="motif_1" pvalue="4.7e-05" match="+++++ +  ++ +      + "/>
			</seg>
		</sequence>
		<sequence id="seq_1_19" db="db_1" num="19" name="NODG_RHIME" comment="NODULATION PROTEIN G (HOST-SPECIFICITY OF NODULATION PROTEIN C)" length="245">
			<score strand="both" combined_pvalue="9.69e-36" evalue="3.2e-34"/>
			<seg start="1">
				<data>
MFELTGRKALVTGASGAIGGAIARVLHAQGAIVGLHGTQIEKLETLATELGDRVKLFPANLANRDEVKALGQRAE
ADLEGVDILVNNAGITKDGLFLHMADPDWDIVLEVNLTAMFRLTREITQQMIRRRNGRIINVTSVAGAIGNPGQT
NYCASKAGMIGFSKSLAQEIATRNITVNCVAPGFIESAMTDKLNHKQKEKIMVAIPIHRMGTGTEVASAVAYLAS
DHAAYVTGQTIHVNGGMAMI
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="1.8e-14" match="+ +++++++++ ++ ++++ +"/>
				<hit pos="58" gap="31" motif="motif_2" pvalue="7.7e-05" match="++  +    ++++ + +  ++    + ++"/>
				<hit pos="150" gap="63" motif="motif_2" pvalue="1.3e-28" match="+++++++++++++++++++++++ +++++"/>
				<hit pos="211" gap="32" motif="motif_2" pvalue="4.3e-05" match="   +    ++  + + ++  +  + ++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_17" db="db_1" num="17" name="HDHA_ECOLI" comment="7-ALPHA-HYDROXYSTEROID DEHYDROGENASE (EC 1.1.1.159) (HSDH)" length="255">
			<score strand="both" combined_pvalue="1.23e-35" evalue="4.1e-34"/>
			<seg start="1">
				<data>
MFNSDNLRLDGKCAIITGAGAGIGKEIAITFATAGASVVVSDINADAANHVVDEIQQLGGQAFACRCDITSEQEL
SALADFAISKLGKVDILVNNAGGGGPKPFDMPMADFRRAYELNVFSFFHLSQLVAPEMEKNGGGVILTITSMAAE
				</data>
				<hit pos="11" gap="10" motif="motif_1" pvalue="5.3e-18" match="++++++++++ ++++++++++"/>
				<hit pos="35" gap="3" motif="motif_1" pvalue="7.7e-05" match="+  +++   +     + + + "/>
				<hit pos="66" gap="10" motif="motif_2" pvalue="7.9e-05" match="     + + ++++   +   +++  + ++"/>
				<hit pos="113" gap="18" motif="motif_2" pvalue="9.6e-07" match=" ++    ++  ++++  + ++ + +  + "/>
			</seg>
			<seg start="151">
				<data>
NKNINMTSYASSKAAASHLVRNMAFDLGEKNIRVNGIAPGAILTDALKSVITPEIEQKMLQHTPIRRLGQPQDIA
				</data>
				<hit pos="157" gap="15" motif="motif_2" pvalue="5.1e-25" match="+++ +++++ +++++ +++++++++++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_10" db="db_1" num="10" name="DHGB_BACME" comment="GLUCOSE 1-DEHYDROGENASE B (EC 1.1.1.47)" length="262">
			<score strand="both" combined_pvalue="1.35e-35" evalue="4.5e-34"/>
			<seg start="1">
				<data>
MYKDLEGKVVVITGSSTGLGKSMAIRFATEKAKVVVNYRSKEDEANSVLEEEIKKVGGEAIAVKGDVTVESDVIN
LVQSAIKEFGKLDVMINNAGMENPVSSHEMSLSDWNKVIDTNLTGAFLGSREAIKYFVENDIKGTVINMSSVHEW
				</data>
				<hit pos="7" gap="6" motif="motif_1" pvalue="9.3e-17" match="++++++++++ ++++++++++"/>
				<hit pos="64" gap="36" motif="motif_2" pvalue="3.8e-05" match="         ++++++++ ++ ++  + ++"/>
				<hit pos="111" gap="18" motif="motif_1" pvalue="7.9e-05" match="++++     +  ++   ++  "/>
			</seg>
			<seg start="151">
				<data>
KIPWPLFVHYAASKGGMKLMTETLALEYAPKGIRVNNIGPGAINTPINAEKFADPEQRADVESMIPMGYIGEPEE
IAAVAWLASSEASYVTGITLFADGGMTQYPSFQAGRG
				</data>
				<hit pos="158" gap="26" motif="motif_2" pvalue="3.0e-26" match=" ++ +++++++ +++++++++++++++++"/>
				<hit pos="225" gap="38" motif="motif_1" pvalue="8.7e-05" match="  +++   +++   + + +++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_24" db="db_1" num="24" name="DHB2_HUMAN" comment="no comment" length="387">
			<score strand="both" combined_pvalue="3.69e-34" evalue="1.2e-32"/>
			<seg start="76">
				<data>
ELLPVDQKAVLVTGGDCGLGHALCKYLDELGFTVFAGVLNENGPGAEELRRTCSPRLSVLQMDITKPVQIKDAYS
				</data>
				<hit pos="82" gap="81" motif="motif_1" pvalue="1.5e-17" match="+++++++++++++++++++++"/>
			</seg>
			<seg start="151">
				<data>
KVAAMLQDRGLWAVINNAGVLGFPTDGELLLMTDYKQCMAVNFFGTVEVTKTFLPLLRKSKGRLVNVSSMGGGAP
				</data>
				<hit pos="187" gap="84" motif="motif_2" pvalue="3.8e-05" match="  +    ++ +  +++    ++++  +  "/>
			</seg>
			<seg start="226">
				<data>
MERLASYGSSKAAVTMFSSVMRLELSKWGIKVASIQPGGFLTNIAGTSDKWEKLEKDILDHLPAEVQEDYGQDYI
				</data>
				<hit pos="230" gap="14" motif="motif_2" pvalue="2.3e-24" match="+++++++++++++++ ++++++++++++ "/>
			</seg>
			<seg start="301">
				<data>
LAQRNFLLLINSLASKDFSPVLRDIQHAILAKSPFAYYTPGKGAYLWICLAHYLPIGIYDYFAKRHFGQDKPMPR
				</data>
				<hit pos="336" gap="77" motif="motif_2" pvalue="1.2e-05" match="+ ++  +++    + ++ + ++ +     "/>
			</seg>
		</sequence>
		<sequence id="seq_1_16" db="db_1" num="16" name="HDE_CANTR" comment="HYDRATASE-DEHYDROGENASE-EPIMERASE (HDE)" length="906">
			<score strand="both" combined_pvalue="3.86e-34" evalue="1.3e-32"/>
			<seg start="1">
				<data>
MSPVDFKDKVVIITGAGGGLGKYYSLEFAKLGAKVVVNDLGGALNGQGGNSKAADVVVDEIVKNGGVAVADYNNV
				</data>
				<hit pos="8" gap="7" motif="motif_1" pvalue="4.7e-15" match="+++++++++++++++ +++++"/>
			</seg>
			<seg start="151">
				<data>
PAGLYGNFGQANYASAKSALLGFAETLAKEGAKYNIKANAIAPLARSRMTESILPPPMLEKLGPEKVAPLVLYLS
				</data>
				<hit pos="161" gap="132" motif="motif_2" pvalue="5.4e-18" match="+++ +++ ++ ++ ++++++ ++++++ +"/>
				<hit pos="197" gap="7" motif="motif_2" pvalue="7.0e-05" match="+ ++ +     ++ +     +++   + +"/>
			</seg>
			<seg start="301">
				<data>
TNEARKLPANDASGAPTVSLKDKVVLITGAGAGLGKEYAKWFAKYGAKVVVNDFKDATKTVDEIKAAGGEAWPDQ
				</data>
				<hit pos="322" gap="96" motif="motif_1" pvalue="8.8e-19" match="++++++++++ ++++++++++"/>
			</seg>
			<seg start="451">
				<data>
NITSTSGIYGNFGQANYSSSKAGILGLSKTMAIEGAKNNIKVNIVAPHAETAMTLTIFREQDKNLYHADQVAPLL
VYLGTDDVPVTGETSEIGGGWIGNTRWQRAKGAVSHDEHTTVEFIKEHLNEITDFTTDTENPKSTTESSMAILSA
				</data>
				<hit pos="465" gap="122" motif="motif_2" pvalue="6.9e-24" match="++++++++++ +++++++ + ++ +++++"/>
				<hit pos="501" gap="7" motif="motif_2" pvalue="1.8e-05" match="++++ + +  +    +++ ++++  ++  "/>
				<hit pos="550" gap="20" motif="motif_2" pvalue="1.3e-05" match="+    +++++++  ++    ++++   ++"/>
			</seg>
			<seg start="676">
				<data>
FNSGKSQNSFAKLLRNFNPMLLLHGEHYLKVHSWPPPTEGEIKTTFEPIATTPKGTNVVIVHGSKSVDNKSGELI
				</data>
				<hit pos="730" gap="151" motif="motif_1" pvalue="4.5e-06" match="+ ++++  +++ +     +  "/>
			</seg>
		</sequence>
		<sequence id="seq_1_11" db="db_1" num="11" name="DHII_HUMAN" comment="CORTICOSTEROID 11-BETA-DEHYDROGENASE (EC 1.1.1.146) (11-DH) (11-BETA- HYDROXYSTEROID DEHYDROGENASE) (11-BETA-HSD)" length="292">
			<score strand="both" combined_pvalue="1.50e-33" evalue="5e-32"/>
			<seg start="1">
				<data>
MAFMKKYLLPILGLFMAYYYYSANEEFRPEMLQGKKVIVTGASKGIGREMAYHLAKMGAHVVVTARSKETLQKVV
SHCLELGAASAHYIAGTMEDMTFAEQFVAQAGKLMGGLDMLILNHITNTSLNLFHDDIHHVRKSMEVNFLSYVVL
				</data>
				<hit pos="34" gap="33" motif="motif_1" pvalue="2.8e-19" match="+++++++++++++++++++++"/>
				<hit pos="58" gap="3" motif="motif_1" pvalue="1.2e-05" match="+ +++++  ++      + ++"/>
			</seg>
			<seg start="151">
				<data>
TVAALPMLKQSNGSIVVVSSLAGKVAYPMVAAYSASKFALDGFFSSIRKEYSVSRVNVSITLCVLGLIDTETAMK
				</data>
				<hit pos="181" gap="102" motif="motif_2" pvalue="9.3e-22" match="+++++++++++++ ++ +++++ ++++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_12" db="db_1" num="12" name="DHMA_FLAS1" comment="N-ACYLMANNOSAMINE 1-DEHYDROGENASE (EC 1.1.1.233) (NAM-DH) " length="270">
			<score strand="both" combined_pvalue="1.65e-33" evalue="5.4e-32"/>
			<seg start="1">
				<data>
TTAGVSRRPGRLAGKAAIVTGAAGGIGRATVEAYLREGASVVAMDLAPRLAATRYEEPGAIPIACDLADRAAIDA
				</data>
				<hit pos="14" gap="13" motif="motif_1" pvalue="1.3e-16" match="++++++++++++++++++++ "/>
				<hit pos="35" gap="0" motif="motif_2" pvalue="2.8e-05" match="   +++  +++   + ++  + + +    "/>
			</seg>
			<seg start="76">
				<data>
AMADAVARLGGLDILVAGGALKGGTGNFLDLSDADWDRYVDVNMTGTFLTCRAGARMAVAAGAGKDGRSARIITI
				</data>
				<hit pos="86" gap="22" motif="motif_1" pvalue="1.0e-05" match="+  +++ +++   +    +++"/>
				<hit pos="129" gap="22" motif="motif_1" pvalue="1.3e-05" match="+ ++ +  +++  +++  +  "/>
			</seg>
			<seg start="151">
				<data>
GSVNSFMAEPEAAAYVAAKGGVAMLTRAMAVDLARHGILVNMIAPGPVDVTGNNTGYSEPRLAEQVLDEVALGRP
				</data>
				<hit pos="163" gap="13" motif="motif_2" pvalue="2.7e-24" match="+++ ++++++ +++++++++++++++ ++"/>
			</seg>
			<seg start="226">
				<data>
GLPEEVATAAVFLAEDGSSFITGSTITIDGGLSAMIFGGMREGRR
				</data>
				<hit pos="241" gap="49" motif="motif_1" pvalue="3.0e-05" match="+    ++++   +   ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_28" db="db_1" num="28" name="FVT1_HUMAN" comment="no comment" length="332">
			<score strand="both" combined_pvalue="2.42e-33" evalue="8e-32"/>
			<seg start="1">
				<data>
MLLLAAAFLVAFVLLLYMVSPLISPKPLALPGAHVVVTGGSSGIGKCIAIECYKQGAFITLVARNEDKLLQAKKE
				</data>
				<hit pos="32" gap="31" motif="motif_1" pvalue="1.4e-16" match="+ +++++++++++++++++++"/>
			</seg>
			<seg start="151">
				<data>
YPSRAVITTMKERRVGRIVFVSSQAGQLGLFGFTAYSASKFAIRGLAEALQMEVKPYNVYITVAYPPDTDTPGFA
				</data>
				<hit pos="184" gap="131" motif="motif_2" pvalue="2.3e-24" match="+++++++++++++ +++++++++++++++"/>
			</seg>
			<seg start="226">
				<data>
EENRTKPLETRLISETTSVCKPEQVAKQIVKDAIQGNFNSSLGSDGYMLSALTCGMAPVTSITEGLQQVVTMGLF
RTIALFYLGSFDSIVRRCMMQREKSENADKTA
				</data>
				<hit pos="275" gap="62" motif="motif_2" pvalue="5.4e-05" match="++ +   + +++ ++ +++ +     +  "/>
			</seg>
		</sequence>
		<sequence id="seq_1_20" db="db_1" num="20" name="RIDH_KLEAE" comment="RIBITOL 2-DEHYDROGENASE (EC 1.1.1.56) (RDH)" length="249">
			<score strand="both" combined_pvalue="2.76e-33" evalue="9.1e-32"/>
			<seg start="1">
				<data>
MKHSVSSMNTSLSGKVAAITGAASGIGLECARTLLGAGAKVVLIDREGEKLNKLVAELGENAFALQVDLMQADQV
				</data>
				<hit pos="14" gap="13" motif="motif_1" pvalue="1.2e-17" match="++++ ++++++++++++++++"/>
				<hit pos="39" gap="4" motif="motif_1" pvalue="1.7e-05" match=" +++++   +  + +  ++  "/>
			</seg>
			<seg start="151">
				<data>
VVPVIWEPVYTASKFAVQAFVHTTRRQVAQYGVRVGAVLPGPVVTALLDDWPKAKMDEALANGSLMQPIEVAESV
				</data>
				<hit pos="158" gap="98" motif="motif_2" pvalue="5.7e-23" match="++++++++++++++++ +++++++++++ "/>
			</seg>
		</sequence>
		<sequence id="seq_1_21" db="db_1" num="21" name="YINL_LISMO" comment="HYPOTHETICAL 26.8 KD PROTEIN IN INLA 5'REGION (ORFA)" length="248">
			<score strand="both" combined_pvalue="3.41e-33" evalue="1.1e-31"/>
			<seg start="1">
				<data>
MTIKNKVIIITGASSGIGKATALLLAEKGAKLVLAARRVEKLEKIVQIIKANSGEAIFAKTDVTKREDNKKLVEL
				</data>
				<hit pos="5" gap="4" motif="motif_1" pvalue="5.4e-20" match="+++++++++++++++++++ +"/>
				<hit pos="43" gap="17" motif="motif_1" pvalue="5.7e-05" match=" + + +  ++++       + "/>
			</seg>
			<seg start="151">
				<data>
GAVYGATKWAVRDLMEVLRMESAQEGTNIRTATIYPAAINTELLETITDKETEQGMTSLYKQYGITPDRIASIVA
				</data>
				<hit pos="152" gap="88" motif="motif_2" pvalue="1.6e-20" match="+++++++++++ +++ ++++ ++++ +++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_1" db="db_1" num="1" name="2BHD_STREX" comment="20-BETA-HYDROXYSTEROID DEHYDROGENASE (EC 1.1.1.53)" length="255">
			<score strand="both" combined_pvalue="7.12e-33" evalue="2.4e-31"/>
			<seg start="1">
				<data>
MNDLSGKTVIITGGARGLGAEAARQAVAAGARVVLADVLDEEGAATARELGDAARYQHLDVTIEEDWQRVVAYAR
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="1.1e-14" match="++++++++++++++ + +++ "/>
				<hit pos="30" gap="3" motif="motif_1" pvalue="1.2e-06" match="+ +++        + ++++++"/>
			</seg>
			<seg start="76">
				<data>
EEFGSVDGLVNNAGISTGMFLETESVERFRKVVDINLTGVFIGMKTVIPAMKDAGGGSIVNISSAAGLMGLALTS
SYGASKWGVRGLSKLAAVELGTDRIRVNSVHPGMTYTPMTAETGIRQGEGNYPNTPMGRVGNEPGEIAGAVVKLL
				</data>
				<hit pos="105" gap="54" motif="motif_1" pvalue="1.7e-05" match=" +++ +   +  ++  +++  "/>
				<hit pos="150" gap="24" motif="motif_2" pvalue="1.5e-25" match="+++++++++++++++ +++++++ +++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_29" db="db_1" num="29" name="HMTR_LEIMA" comment="no comment" length="287">
			<score strand="both" combined_pvalue="1.68e-32" evalue="5.5e-31"/>
			<seg start="1">
				<data>
MTAPTVPVALVTGAAKRLGRSIAEGLHAEGYAVCLHYHRSAAEANALSATLNARRPNSAITVQADLSNVATAPVS
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="3.5e-14" match=" ++++++++++ +++++++ +"/>
				<hit pos="35" gap="8" motif="motif_2" pvalue="1.0e-05" match=" ++  + +   +++ ++      + ++++"/>
			</seg>
			<seg start="76">
				<data>
GADGSAPVTLFTRCAELVAACYTHWGRCDVLVNNASSFYPTPLLRNDEDGHEPCVGDREAMETATADLFGSNAIA
				</data>
				<hit pos="81" gap="17" motif="motif_1" pvalue="1.0e-05" match=" ++ + + ++  +  ++ ++ "/>
			</seg>
			<seg start="151">
				<data>
PYFLIKAFAHRSRHPSQASRTNYSIINMVDAMTNQPLLGYTIYTMAKGALEGLTRSAALELAPLQIRVNGVGPGL
				</data>
				<hit pos="191" gap="89" motif="motif_2" pvalue="8.9e-26" match="+ +++++++++++++++++++++ +++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_13" db="db_1" num="13" name="ENTA_ECOLI" comment="2,3-DIHYDRO-2,3-DIHYDROXYBENZOATE DEHYDROGENASE (EC 1.3.1.28)" length="248">
			<score strand="both" combined_pvalue="1.10e-31" evalue="3.6e-30"/>
			<seg start="1">
				<data>
MDFSGKNVWVTGAGKGIGYATALAFVEAGAKVTGFDQAFTQEQYPFATEVMDVADAAQVAQVCQRLLAETERLDA
				</data>
				<hit pos="5" gap="4" motif="motif_1" pvalue="1.0e-18" match="+++++++++++++++++++++"/>
			</seg>
			<seg start="76">
				<data>
LVNAAGILRMGATDQLSKEDWQQTFAVNVGGAFNLFQQTMNQFRRQRGGAIVTVASDAAHTPRIGMSAYGASKAA
LKSLALSVGLELAGSGVRCNVVSPGSTDTDMQRTLWVSDDAEEQRIRGFGEQFKLGIPLGKIARPQEIANTILFL
				</data>
				<hit pos="98" gap="72" motif="motif_1" pvalue="6.5e-05" match="+  ++  +++  +   +  ++"/>
				<hit pos="142" gap="23" motif="motif_2" pvalue="2.9e-20" match="+++++++++++++  +  ++++ ++++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_6" db="db_1" num="6" name="BDH_HUMAN" comment="D-BETA-HYDROXYBUTYRATE DEHYDROGENASE PRECURSOR (EC 1.1.1.30) (BDH) (3-HYDROXYBUTYRATE DEHYDROGENASE) (FRAGMENT)" length="343">
			<score strand="both" combined_pvalue="1.22e-31" evalue="4e-30"/>
			<seg start="1">
				<data>
GLRPPPPGRFSRLPGKTLSACDRENGARRPLLLGSTSFIPIGRRTYASAAEPVGSKAVLVTGCDSGFGFSLAKHL
				</data>
				<hit pos="55" gap="54" motif="motif_1" pvalue="5.0e-17" match="++++++++++++ ++++++++"/>
			</seg>
			<seg start="151">
				<data>
GEVEFTSLETYKQVAEVNLWGTVRMTKSFLPLIRRAKGRVVNISSMLGRMANPARSPYCITKFGVEAFSDCLRYE
MYPLGVKVSVVEPGNFIAATSLYNPESIQAIAKKMWEELPEVVRKDYGKKYFDEKIAKMETYCSSGSTDTSPVID
				</data>
				<hit pos="206" gap="130" motif="motif_2" pvalue="3.1e-22" match="++++ +++++++++ ++++++++ +++++"/>
				<hit pos="252" gap="17" motif="motif_2" pvalue="3.6e-06" match="+    ++   + + +  +++++++     "/>
			</seg>
		</sequence>
		<sequence id="seq_1_15" db="db_1" num="15" name="GUTD_ECOLI" comment="SORBITOL-6-PHOSPHATE 2-DEHYDROGENASE (EC 1.1.1.140) (GLUCITOL-6- PHOSPHATE DEHYDROGENASE) (KETOSEPHOSPHATE REDUCTASE)" length="259">
			<score strand="both" combined_pvalue="6.59e-31" evalue="2.2e-29"/>
			<seg start="1">
				<data>
MNQVAVVIGGGQTLGAFLCHGLAAEGYRVAVVDIQSDKAANVAQEINAEYGESMAYGFGADATSEQSCLALSRGV
				</data>
				<hit pos="2" gap="1" motif="motif_1" pvalue="7.7e-12" match="++++++ ++++ ++  +++ +"/>
			</seg>
			<seg start="76">
				<data>
DEIFGRVDLLVYSAGIAKAAFISDFQLGDFDRSLQVNLVGYFLCAREFSRLMIRDGIQGRIIQINSKSGKVGSKH
				</data>
				<hit pos="87" gap="64" motif="motif_2" pvalue="1.5e-05" match="++ + ++++ ++  +   ++ + +   + "/>
			</seg>
			<seg start="151">
				<data>
NSGYSAAKFGGVGLTQSLALDLAEYGITVHSLMLGNLLKSPMFQSLLPQYATKLGIKPDQVEQYYIDKVPLKRGC
				</data>
				<hit pos="152" gap="36" motif="motif_2" pvalue="2.1e-26" match="+ +++++++ +++++++++++++++++++"/>
			</seg>
			<seg start="226">
				<data>
DYQDVLNMLLFYASPKASYCTGQSINVTGGQVMF
				</data>
				<hit pos="230" gap="49" motif="motif_1" pvalue="5.2e-05" match="  +++   ++    +++    "/>
			</seg>
		</sequence>
		<sequence id="seq_1_9" db="db_1" num="9" name="DHES_HUMAN" comment="ESTRADIOL 17 BETA-DEHYDROGENASE (EC 1.1.1.62) (20 ALPHA-HYDROXYSTEROID DEHYDROGENASE) (E2DH) (17-BETA-HSD) (PLACENTAL 17-BETA-HYDROXYSTEROID DEHYDROGENASE)" length="327">
			<score strand="both" combined_pvalue="1.09e-30" evalue="3.6e-29"/>
			<seg start="1">
				<data>
ARTVVLITGCSSGIGLHLAVRLASDPSQSFKVYATLRDLKTQGRLWEAARALACPPGSLETLQLDVRDSKSVAAA
				</data>
				<hit pos="2" gap="1" motif="motif_1" pvalue="3.4e-16" match="  ++++++++++++++++ ++"/>
			</seg>
			<seg start="76">
				<data>
RERVTEGRVDVLVCNAGLGLLGPLEALGEDAVASVLDVNVVGTVRMLQAFLPDMKRRGSGRVLVTGSVGGLMGLP
				</data>
				<hit pos="86" gap="63" motif="motif_2" pvalue="1.5e-05" match="   + +  ++ +  +++  +   +   ++"/>
			</seg>
			<seg start="151">
				<data>
FNDVYCASKFALEGLCESLAVLLLPFGVHLSLIECGPVHTAFMEKVLGSPEEVLDRTDIHTFHRFYQYLAHSKQV
				</data>
				<hit pos="153" gap="38" motif="motif_2" pvalue="4.7e-22" match=" ++++++++++++++++++ + + +++ +"/>
			</seg>
			<seg start="226">
				<data>
FREAAQNPEEVAEVFLTALRAPKPTLRYFTTERFLPLLRMRLDDPSGSNYVTAMHREVFGDVPAKAEAGAEAGGG
				</data>
				<hit pos="242" gap="60" motif="motif_2" pvalue="9.5e-05" match="++  + +  ++ ++ +  + + + +    "/>
			</seg>
		</sequence>
		<sequence id="seq_1_5" db="db_1" num="5" name="BA72_EUBSP" comment="7-ALPHA-HYDROXYSTEROID DEHYDROGENASE (EC 1.1.1.159) (BILE ACID 7-DEHYDROXYLASE) (BILE ACID-INDUCIBLE PROTEIN)" length="249">
			<score strand="both" combined_pvalue="5.90e-30" evalue="1.9e-28"/>
			<seg start="1">
				<data>
MNLVQDKVTIITGGTRGIGFAAAKIFIDNGAKVSIFGETQEEVDTALAQLKELYPEEEVLGFAPDLTSRDAVMAA
VGQVAQKYGRLDVMINNAGITSNNVFSRVSEEEFKHIMDINVTGVFNGAWCAYQCMKDAKKGVIINTASVTGIFG
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="2.8e-16" match="+++ +++++ ++++++ ++ +"/>
				<hit pos="63" gap="36" motif="motif_2" pvalue="4.4e-06" match="++   +  ++ + +   ++ +++  + ++"/>
			</seg>
			<seg start="151">
				<data>
SLSGVGYPASKASVIGLTHGLGREIIRKNIRVVGVAPGVVNTDMTNGNPPEIMEGYLKALPMKRMLEPEEIANVY
				</data>
				<hit pos="155" gap="63" motif="motif_2" pvalue="5.7e-21" match="  + +++++++++++ + +++ ++++++ "/>
			</seg>
		</sequence>
		<sequence id="seq_1_2" db="db_1" num="2" name="3BHD_COMTE" comment="3-BETA-HYDROXYSTEROID DEHYDROGENASE (EC 1.1.1.51)" length="253">
			<score strand="both" combined_pvalue="9.42e-30" evalue="3.1e-28"/>
			<seg start="1">
				<data>
TNRLQGKVALVTGGASGVGLEVVKLLLGEGAKVAFSDINEAAGQQLAAELGERSMFVRHDVSSEADWTLVMAAVQ
RRLGTLNVLVNNAGILLPGDMETGRLEDFSRLLKINTESVFIGCQQGIAAMKETGGSIINMASVSSWLPIEQYAG
YSASKAAVSALTRAAALSCRKQGYAIRVNSIHPDGIYTPMMQASLPKGVSKEMVLHDPKLNRAGRAYMPERIAQL
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="6.8e-17" match="++++++++++++++++ ++ +"/>
				<hit pos="30" gap="3" motif="motif_1" pvalue="1.1e-05" match="+ ++     +   +  ++ ++"/>
				<hit pos="58" gap="7" motif="motif_2" pvalue="2.0e-06" match=" +  ++ +  +  + + ++ +++ ++ ++"/>
				<hit pos="149" gap="62" motif="motif_2" pvalue="3.6e-20" match="+ +++++++++++++++++ +++++  ++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_25" db="db_1" num="25" name="DHB3_HUMAN" comment="no comment" length="310">
			<score strand="both" combined_pvalue="7.86e-29" evalue="2.6e-27"/>
			<seg start="1">
				<data>
MGDVLEQFFILTGLLVCLACLAKCVRFSRCVLLNYYKVLPKSFLRSMGQWAVITGAGDGIGKAYSFELAKRGLNV
				</data>
				<hit pos="48" gap="47" motif="motif_1" pvalue="2.1e-16" match="++++++++++ +++++++ ++"/>
			</seg>
			<seg start="151">
				<data>
QSLIHCNITSVVKMTQLILKHMESRQKGLILNISSGIALFPWPLYSMYSASKAFVCAFSKALQEEYKAKEVIIQV
				</data>
				<hit pos="196" gap="127" motif="motif_2" pvalue="6.6e-20" match="++++++++++++++++++ +++ + + ++"/>
			</seg>
			<seg start="226">
				<data>
LTPYAVSTAMTKYLNTNVITKTADEFVKESLNYVTIGGETCGCLAHEILAGFLSLIPAWAFYSGAFQRLLLTHYV
AYLKLNTKVR
				</data>
				<hit pos="227" gap="2" motif="motif_2" pvalue="1.8e-05" match="+++  + +  + +        + + ++ +"/>
				<hit pos="282" gap="26" motif="motif_2" pvalue="2.9e-06" match="++     ++ + +  ++ + + + + +++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_32" db="db_1" num="32" name="RFBB_NEIGO" comment="no comment" length="346">
			<score strand="both" combined_pvalue="1.30e-26" evalue="4.3e-25"/>
			<seg start="1">
				<data>
MQTEGKKNILVTGGAGFIGSAVVRHIIQNTRDSVVNLDKLTYAGNLESLTDIADNPRYAFEQVDICDRAELDRVF
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="2.9e-14" match="+++++++++++ ++ + +++ "/>
			</seg>
			<seg start="151">
				<data>
DLFTETTPYAPSSPYSASKAAADHLVRAWQRTYRLPSIVSNCSNNYGPRQFPEKLIPLMILNALSGKPLPVYGDG
				</data>
				<hit pos="163" gap="136" motif="motif_2" pvalue="6.6e-20" match="+++++++++ +++++++++ ++   ++ +"/>
			</seg>
			<seg start="226">
				<data>
AQIRDWLFVEDHARALYQVVTEGVVGETYNIGGHNEKTNLEVVKTICALLEELAPEKPAGVARYEDLITFVQDRP
				</data>
				<hit pos="240" gap="48" motif="motif_2" pvalue="4.2e-05" match="+ +     ++++ +        +++  + "/>
			</seg>
		</sequence>
		<sequence id="seq_1_18" db="db_1" num="18" name="LIGD_PSEPA" comment="C ALPHA-DEHYDROGENASE (EC -.-.-.-)" length="305">
			<score strand="both" combined_pvalue="1.31e-26" evalue="4.3e-25"/>
			<seg start="1">
				<data>
MKDFQDQVAFITGGASGAGFGQAKVFGQAGAKIVVADVRAEAVEKAVAELEGLGITAHGIVLDIMDREAYARAAD
				</data>
				<hit pos="6" gap="5" motif="motif_1" pvalue="3.5e-14" match="++++ +++++++ ++ +++ +"/>
			</seg>